name: fablesofdesire
description: A new game.
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  share: ^2.0.1
  package_info: ^2.0.0
  provider: ^5.0.0
  path_provider: ^2.0.1
  animated_text_kit: ^4.2.0
  flutter_launcher_icons: ^0.9.0
  easy_localization: ^3.0.0
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  flame_audio: ^0.1.0-rc5
  page_transition: ^2.0.1-nullsafety.0

# dependency_overrides:
#   games_services:
#     git:
#       url: https://github.com/jonatadashi/games_services.git
#       ref: master
#       path: games_services
flutter_icons:
  android: "launcher_icon" 
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/sprites/MC_Blush.png"

flutter:

  uses-material-design: true

  assets:
    - assets/audio/

    - assets/images/
    - assets/images/sprites/

    - assets/languages/

  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf