name: fablesofdesire
description: A new game.
version: 1.0.0+1
publish_to: none

authors:
  - Jona T. Feucht <hey@jona.space>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.4
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  share: ^2.0.1
  package_info: ^2.0.0
  provider: ^5.0.0
  path_provider: ^2.0.1
  simple_animations: ^3.0.3
  animated_text_kit: ^4.2.0
  bubble: ^1.2.1
  flutter_launcher_icons: ^0.9.0
  purchases_flutter: ^3.2.1
  easy_localization: ^3.0.0
  hive: ^2.0.3
  flutter_svg: ^0.21.0+1
  rflutter_alert: ^2.0.2
  hive_flutter: ^1.0.0
  google_fonts: ^2.0.0
  flame: ^1.0.0-rc9
  flame_audio: ^0.1.0-rc5
  page_transition: ^2.0.1-nullsafety.0
  get: ^4.1.4
  #rive: ^0.6.8

dependency_overrides:
  games_services:
    git:
      url: https://github.com/jonatadashi/games_services.git
      ref: master
      path: games_services

  #audioplayers: any
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"
  
flutter:

  uses-material-design: true

  assets:
    - assets/audio/

    - assets/images/
    - assets/images/sprites/

    - assets/languages/

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: PxGrotesk
      fonts:
        - asset: assets/fonts/Px-Grotesk-Regular.ttf
    - family: PalanquinDark
      fonts:
        - asset: assets/fonts/PalanquinDark-Regular.ttf
