name: fablesofdesire
description: A new game.
publish_to: 'none' 
version: 1.0.0+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  share: ^2.0.1
  package_info: ^2.0.0
  animated_text_kit: ^4.2.1
  flutter_launcher_icons: ^0.9.0
  easy_localization: ^3.0.0
  flame_audio: ^0.1.0-rc5
  msix: ^2.0.0
  universal_io: ^2.0.4
  dart_vlc: ^0.0.6

# dependency_overrides:
#   dart_vlc:
#     git:
#       url: https://github.com/jonatadashi/games_services.git
#       ref: master
#       path: games_services

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon" 
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/sprites/Cast/MC_Happy.png"

flutter:

  uses-material-design: true

  assets:
    - assets/audio/

    - assets/images/
    - assets/images/sprites/
    - assets/images/sprites/Cast/
    - assets/images/sprites/Cast/Tomiichi/
    - assets/images/sprites/Cast/Naoki/
    - assets/images/sprites/Cast/Hidetake/
    - assets/images/gui/
    - assets/images/bgs/

    - assets/languages/

  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf
    - family: NanumBrush
      fonts:
        - asset: assets/fonts/NanumBrushScript-Regular.ttf
    - family: Julee
      fonts:
        - asset: assets/fonts/Julee-Regular.ttf

# flutter pub run msix:create
msix_config:
  display_name: Fables of Desire
  publisher_display_name: SmallDreams
  identity_name: 35475SmallDreams.FablesofDesire
  publisher: CN=E96D5E05-B3DD-4875-8CF1-5DA32F770BCE
  logo_path: windows\runner\resources\app_icon.png
  start_menu_icon_path: windows\runner\resources\app_icon.png
  tile_icon_path: windows\runner\resources\app_icon.png
  certificate_path: C:\Users\jonaf\OneDrive\Documents\keys\openssl\fablesofdesire\CERT.pfx
  certificate_password: fablesofdesire
  msix_version: 1.1.1.0
  icons_background_color: "#ffffff"
  architecture: x64
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations