# name: CI
# on:
#     pull_request:
#       branches:
#         - main
#         - alpha
#         - beta
#     push:
#       branches:
#         - develop

# jobs:
#   build_android:
#     name: Build Android
#     runs-on: macos-latest
#     timeout-minutes: 30
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter build appbundle

#   build_ios:
#     name: Build iOS
#     runs-on: macos-latest
#     timeout-minutes: 30
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter build ios --no-codesign
    
#   build_macos:
#     name: Build macOS
#     runs-on: macos-latest
#     timeout-minutes: 30
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - run: flutter pub get
#       - run: flutter config --enable-macos-desktop
#       - run: flutter build macos

#   build_windows:
#     name: Build Windows
#     runs-on: windows-latest
#     timeout-minutes: 30
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v1
#       - name: Set up Java
#         uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v1
#         with:
#           channel: "beta"
#       - name: Install pub Dependencies
#         run: flutter pub get
#       - name: Build Windows
#         run: |
#           flutter config --enable-windows-desktop
#           flutter build windows

#       # - name: Upload build artifacts
#       #   uses: actions/upload-artifact@v1
#       #   with:
#       #     name: windows build
#       #     path: build/windows/runner/Release
